PTFM-17905 Retry AttributeError in DXHTTPRequest
Summary:
Some customers have been sporadically getting "AttributeError: 'NoneType'
object has no attribute 'readline'" while downloading files. This is due to a
bug in urllib3 on chunked responses. The solution presented here is to retry
this error.

Test Plan: _DX_INJECT_ERROR=1 flag on nucleus integration tests

Reviewers: orodeh

Differential Revision: https://dnanexus.phacility.com/D953